# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-26 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='occupant',
            name='user_id',
            field=models.IntegerField(unique=True),
        ),
    ]
