# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0009_post_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='image',
            field=models.ImageField(default=1, upload_to='businesses/'),
            preserve_default=False,
        ),
    ]
