# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-26 14:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0004_post_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Occupant',
            new_name='Profile',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='occupant',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='occupant',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='neighourhood',
            new_name='neighbourhood',
        ),
    ]
