# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-26 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0006_auto_20180526_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='occupant_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
