# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-26 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0007_auto_20180526_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_caption',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
