# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-28 06:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0008_post_post_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hood.Business'),
            preserve_default=False,
        ),
    ]
